### ISSUE TITLE
Run python generate code failed

### ISSUE THREAD

**Issue by czgtest** [microsoft/vscode-azure-iot-toolkit#420]
step:
1. create one device in VS Code Toolkit
2. right-click the device and generate code
3. select python
4. install "pip install azure-iothub-device-client"
5. run code failed :
[Running] python -u "d:\f\Untitled-2.py"
Traceback (most recent call last):
  File "d:\f\Untitled-2.py", line 12, in <module>
    import iothub_client
  File "C:\Users\iotedge\AppData\Local\Programs\Python\Python38-32\lib\site-packages\iothub_client\__init__.py", line 1, in <module>
    from .iothub_client import *
ImportError: DLL load failed while importing iothub_client: The specified module could not be found.

[Done] exited with code=1 in 0.383 seconds
![image](https://user-images.githubusercontent.com/35018765/67273066-506a8f80-f4f0-11e9-93a9-4b7ae2036fe5.png)

**Comment by formulahendry** [comment]
Related to https://github.com/Azure/azure-iot-sdk-python/issues/270
