### ISSUE TITLE
Errors: Create Device and detection.node 

### ISSUE THREAD

**Issue by JonathanAsbury-ACS** [microsoft/vscode-azure-iot-toolkit#517]
Like many others, I'm running into issues creating devices using this extension.  The UI looks like this

![image](https://user-images.githubusercontent.com/62960981/116139288-78b1ec00-a69b-11eb-989c-9030f12e2cc2.png)

So far I've tracked down two error trails:
- VS Code console output
- Dev Mode

Appreciate suggestions and happy to hare additional troubleshooting insights.  

**VS Console  console output**
[Device] [Create] error: Error: unable to get local issuer certificate

**Dev Mode**
Don't see anything new while creating devices.  
However, I see a couple of errors related to detection.node is not a valid Win32 application.  See Dev Mode Error Log below for details.

**Alternatives**
Our network uses inbound decryption because of guides like [this]( 
https://www.gartner.com/imagesrv/media-products/pdf/radware/Radware-1-2Y7FR0I.pdf).  So I've tried to different proxy and network configurations but have been unsuccessful.  

**Dev Mode Error Log**
`
Error: \\?\c:\Users\aarkhzz\.vscode\extensions\vsciot-vscode.vscode-iot-device-cube-0.3.0\out\node_modules\usb-detection\build\Release\detection.node is not a valid Win32 application.
\\?\c:\Users\aarkhzz\.vscode\extensions\vsciot-vscode.vscode-iot-device-cube-0.3.0\out\node_modules\usb-detection\build\Release\detection.node
	at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
	at Object.Module._extensions..node (internal/modules/cjs/loader.js:1250:18)
	at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1812)
	at Module.load (internal/modules/cjs/loader.js:1039:32)
	at Module._load (internal/modules/cjs/loader.js:932:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
	at Function.o._load (c:\Users\aarkhzz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:105:27791)
	at Function.E._load (c:\Users\aarkhzz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:105:24509)
	at Function.a._load (c:\Users\aarkhzz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:95:59194)
	at Module.require (internal/modules/cjs/loader.js:1079:19)
	at v (c:\Users\aarkhzz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:694)
	at bindings (c:\Users\aarkhzz\.vscode\extensions\vsciot-vscode.vscode-iot-device-cube-0.3.0\out\node_modules\bindings\bindings.js:112:48)
	at Object.<anonymous> (c:\Users\aarkhzz\.vscode\extensions\vsciot-vscode.vscode-iot-device-cube-0.3.0\out\node_modules\usb-detection\index.js:13:37)
	at Module.u._compile (c:\Users\aarkhzz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1248)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
	at Module.load (internal/modules/cjs/loader.js:1039:32)
	at Module._load (internal/modules/cjs/loader.js:932:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
	at Function.o._load (c:\Users\aarkhzz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:105:27791)
	at Function.E._load (c:\Users\aarkhzz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:105:24509)
	at Function.a._load (c:\Users\aarkhzz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:95:59194)
	at Module.require (internal/modules/cjs/loader.js:1079:19)
	at v (c:\Users\aarkhzz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:694)
	at Object.<anonymous> (c:\Users\aarkhzz\.vscode\extensions\vsciot-vscode.vscode-iot-device-cube-0.3.0\out\node_modules\node-usb-native\lib\detector.js:6:12)
	at Module.u._compile (c:\Users\aarkhzz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1248)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
	at Module.load (internal/modules/cjs/loader.js:1039:32)
	at Module._load (internal/modules/cjs/loader.js:932:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
	at Function.o._load (c:\Users\aarkhzz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:105:27791)
	at Function.E._load (c:\Users\aarkhzz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:105:24509)
	at Function.a._load (c:\Users\aarkhzz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:95:59194)
	at Module.require (internal/modules/cjs/loader.js:1079:19)
	at v (c:\Users\aarkhzz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:694)
	at Object.<anonymous> (c:\Users\aarkhzz\.vscode\extensions\vsciot-vscode.vscode-iot-device-cube-0.3.0\out\node_modules\node-usb-native\lib\index.js:1:82)
	at Module.u._compile (c:\Users\aarkhzz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1248)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
	at Module.load (internal/modules/cjs/loader.js:1039:32)
	at Module._load (internal/modules/cjs/loader.js:932:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
	at Function.o._load (c:\Users\aarkhzz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:105:27791)
	at Function.E._load (c:\Users\aarkhzz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:105:24509)
	at Function.a._load (c:\Users\aarkhzz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:95:59194)
	at Module.require (internal/modules/cjs/loader.js:1079:19)
	at v (c:\Users\aarkhzz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:694)
	at Object.<anonymous> (c:\Users\aarkhzz\.vscode\extensions\vsciot-vscode.vscode-iot-device-cube-0.3.0\out\src\models\serialportctrl.js:13:20)
	at Module.u._compile (c:\Users\aarkhzz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1248)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
	at Module.load (internal/modules/cjs/loader.js:1039:32)
	at Module._load (internal/modules/cjs/loader.js:932:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
	at Function.o._load (c:\Users\aarkhzz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:105:27791)
	at Function.E._load (c:\Users\aarkhzz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:105:24509)
	at Function.a._load (c:\Users\aarkhzz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:95:59194)
	at Module.require (internal/modules/cjs/loader.js:1079:19)
	at v (c:\Users\aarkhzz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:694)
	at c:\Users\aarkhzz\.vscode\extensions\vsciot-vscode.vscode-iot-device-cube-0.3.0\out\node_modules\impor\out\index.js:120:48
$onExtensionRuntimeError @ mainThreadExtensionService.ts:60
`

**Comment by montgomp** [comment]
Are you behind a proxy that could be causing this connectivity issue?
